@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package InternshipLogic as InternshipLogicPackage {
Class "<<interface>>\nInternshipLogic" as InternshipLogic
Class InternshipLogicManager
}

package InternshipModel as InternshipModelPackage {
Class "<<interface>>\nInternshipModel" as InternshipModel
Class InternshipModelManager
}

package InternshipStorage as InternshipStoragePackage {
Class "<<interface>>\nInternshipStorage" as InternshipStorage
Class InternshipStorageManager
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> InternshipLogic

InternshipLogicManager .up.|> InternshipLogic
InternshipModelManager .up.|> InternshipModel
InternshipStorageManager .up.|> InternshipStorage

InternshipLogicManager --> InternshipModel
InternshipLogicManager --> InternshipStorage
@enduml
