@startuml
!include style.puml
skinparam ArrowFontStyle plain

box InternshipLogic LOGIC_COLOR_T1
participant ":InternshipLogicManager" as InternshipLogicManager LOGIC_COLOR
participant ":InternshipDataParser" as InternshipDataParser LOGIC_COLOR
participant ":InternshipDeleteCommandParser" as InternshipDeleteCommandParser LOGIC_COLOR
participant "d:InternshipDeleteCommand" as InternshipDeleteCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box InternshipModel MODEL_COLOR_T1
participant "m:InternshipModel" as InternshipModel MODEL_COLOR
end box

[-> InternshipLogicManager : execute("delete 1")
activate InternshipLogicManager

InternshipLogicManager -> InternshipDataParser : parseCommand("delete 1")
activate InternshipDataParser

create InternshipDeleteCommandParser
InternshipDataParser -> InternshipDeleteCommandParser
activate InternshipDeleteCommandParser

InternshipDeleteCommandParser --> InternshipDataParser
deactivate InternshipDeleteCommandParser

InternshipDataParser -> InternshipDeleteCommandParser : parse("1")
activate InternshipDeleteCommandParser

create InternshipDeleteCommand
InternshipDeleteCommandParser -> InternshipDeleteCommand
activate InternshipDeleteCommand

InternshipDeleteCommand --> InternshipDeleteCommandParser :
deactivate InternshipDeleteCommand

InternshipDeleteCommandParser --> InternshipDataParser : d
deactivate InternshipDeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
InternshipDeleteCommandParser -[hidden]-> InternshipDataParser
destroy InternshipDeleteCommandParser

InternshipDataParser --> InternshipLogicManager : d
deactivate InternshipDataParser

InternshipLogicManager -> InternshipDeleteCommand : execute(m)
activate InternshipDeleteCommand

InternshipDeleteCommand -> InternshipModel : deletePerson(1)
activate InternshipModel

InternshipModel --> InternshipDeleteCommand
deactivate InternshipModel

create CommandResult
InternshipDeleteCommand -> CommandResult
activate CommandResult

CommandResult --> InternshipDeleteCommand
deactivate CommandResult

InternshipDeleteCommand --> InternshipLogicManager : r
deactivate InternshipDeleteCommand

[<--InternshipLogicManager
deactivate InternshipLogicManager
@enduml
