@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":InternshipLogicManager" as InternshipLogicManager LOGIC_COLOR
participant ":InternshipDataParser" as InternshipDataParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> InternshipLogicManager : execute(undo)
activate InternshipLogicManager

InternshipLogicManager -> InternshipDataParser : parseCommand(undo)
activate InternshipDataParser

create UndoCommand
InternshipDataParser -> UndoCommand
activate UndoCommand

UndoCommand --> InternshipDataParser
deactivate UndoCommand

InternshipDataParser --> InternshipLogicManager : u
deactivate InternshipDataParser

InternshipLogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoInternshipData()
activate Model

Model --> UndoCommand
deactivate Model

UndoCommand --> InternshipLogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> InternshipLogicManager : result
destroy UndoCommand

[<--InternshipLogicManager
deactivate InternshipLogicManager
@enduml
