@startuml
!include style.puml
skinparam ArrowFontStyle plain

box InternshipModel MODEL_COLOR_T1
participant ":InternshipModel" as InternshipModel MODEL_COLOR
participant ":VersionedInternshipData" as VersionedInternshipData MODEL_COLOR
end box

[-> InternshipModel : undoInternshipData()
activate InternshipModel

InternshipModel -> VersionedInternshipData : undo()
activate VersionedInternshipData

VersionedInternshipData -> VersionedInternshipData :resetData(ReadOnlyInternshipData)
VersionedInternshipData --> InternshipModel :
deactivate VersionedInternshipData

[<-- InternshipModel
deactivate InternshipModel

@enduml
