@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedInternshipData" as VersionedInternshipData MODEL_COLOR
end box

[-> Model : undoInternshipData()
activate Model

Model -> VersionedInternshipData : undo()
activate VersionedInternshipData

VersionedInternshipData -> VersionedInternshipData :resetData(ReadOnlyInternshipData)
VersionedInternshipData --> Model :
deactivate VersionedInternshipData

[<-- Model
deactivate Model

@enduml
